const irrelevantGenres = [
  'anime',
  'british',
  'brazil',
  'british',
  'cantopop',
  'chicago-house',
  'children',
  'chill',
  'dancehall',
  'detroit-techno',
  'disney',
  'electro',
  'french',
  'garage',
  'german',
  'groove',
  'happy',
  'hardstyle',
  'holidays',
  'idm',
  'indian',
  'indie-pop',
  'iranian',
  'j-dance',
  'j-idol',
  'j-pop',
  'j-rock',
  'kids',
  'latin',
  'malay',
  'mpb',
  'mandopop',
  'metal-misc',
  'minimal-techno',
  'movies',
  'mbp',
  'new-release',
  'party',
  'philippines-opm',
  'piano',
  'pop-film',
  'rainy-day',
  'road-trip',
  'romance',
  'sad',
  'sertanejo',
  'show-tunes',
  'singer-songwriter',
  'sleep',
  'songwriter',
  'spanish',
  'study',
  'summer',
  'swedish',
  'turkish',
  'work-out'
];

const relatedGenres = {
  'alt-rock': ['alternative', 'rock'],
  'alternative': ['alt-rock', 'rock'],
  'black-metal': ['metal'],
  bluegrass: ['country'],
  bossanova: ['latino', 'world-music'],
  country: ['bluegrass', 'honky-tonk'],
  dance: ['edm', 'electronic', 'house', 'progressive-house', 'techno', 'trance'],
  'death-metal': ['metal'],
  'deep-house': ['house'],
  dubstep: ['post-dubstep'],
  edm: ['dance', 'electronic', 'house', 'progressive-house', 'techno', 'trance'],
  electronic: ['edm', 'dance', 'house', 'progressive-house', 'techno', 'trance'],
  forro: ['latino', 'world-music'],
  goth: ['rock'],
  grindcore: ['metal'],
  grunge: ['rock'],
  guitar: ['rock'],
  'hard-rock': ['rock'],
  'heavy-metal': ['metal'],
  'honky-tonk': ['country'],
  house: ['dance', 'edm', 'electronic', 'progressive-house', 'techno'],
  indie: ['rock'],
  'k-pop': ['pop'],
  latino: ['bossanova', 'forro', 'pagode', 'world-music'],
  metal: ['black-metal', 'death-metal', 'heavy-metal', 'metalcore'],
  metalcore: ['metal'],
  'psych-rock': ['rock'],
  pop: ['power-pop', 'synth-pop'],
  'punk': ['punk-rock', 'rock'],
  'punk-rock': ['punk', 'rock'],
  'power-pop': ['pop'],
  'progressive-house': ['dance', 'edm', 'electronic', 'house', 'techno'],
  'psych-rock': ['rock'],
  reggae: ['reggaeton'],
  reggaeton: ['reggae'],
  rock: ['alt-rock', 'alternative', 'goth', 'grunge', 'guitar', 'hard-rock', 'indie', 'psych-rock', 'punk-rock', 'rock-n-roll', 'rockabilly', 'ska'],
  'rock-n-roll': ['rock'],
  rockabilly: ['rock'],
  ska: ['rock'],
  'synth-pop': ['pop'],
  trance: ['dance', 'edm', 'electronic', 'house', 'techno'],
  'world-music': ['bossanova', 'forro', 'latino', 'pagode']
};

export {
  irrelevantGenres,
  relatedGenres
};


